### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by drkitty** [OSURoboticsClub/underwater#1]
The following is not legal advice. Its author(s) are not lawyers.

Typically, a software project adopts a _license_, which states the things non-contributors are allowed to do with the project. By using GitHub for hosting, we accept the [terms of service](https://help.github.com/articles/github-terms-of-service/), which grant people the right to fork and view our repo. If we don't add a license, those are the only things they can do.

Many projects are released under what's known as an _open source_ license. An open source license typically allows anyone to create their own copy of the project, use it, view and modify the source code, and distribute their modifications under certain conditions.

Note that (in most countries, including the U.S.) a project's contributors retain copyright over their contributions as long as they don't explicitly relinquish it. Most open source licenses do not affect copyright.

I'd recommend that we choose an open source license unless we have a good reason not to. It would be easiest if the entire repo were under the same license. Reasonably permissive licenses we might consider include [the BSD two-clause license](http://opensource.org/licenses/BSD-2-Clause) and [the MIT license](http://opensource.org/licenses/MIT).

**Comment by yoos** [comment]
This is a good thing to bring up with the rest of the club so Rover and Aerial can follow suit. Would it be worth organizing a short workshop on this, or is it a simple enough matter we can decide within this issue ticket?

**Comment by drkitty** [comment]
I'm not sure. I doubt most people will be interested in the legal particulars, and in case I'm wrong about that, I don't want this to lead to any kind of bikeshedding—we already have a lot of things to work on. It's important, however, that any two groups who might share code adopt compatible licenses. I suggest we all go with the MIT license unless someone has objections, since it's short, simple, and permissive.

**Comment by drkitty** [comment]
This issue is tentatively resolved, but I'll leave it open so people have a chance to weigh in if they want to.

**Comment by drkitty** [comment]
No one seems to be particularly concerned which license we use.
